name: CI

on:
	push:
		branches: [ "main" ]

jobs:
	lint-and-test:
		runs-on: ubuntu-latest

		steps:
			- name: Copiar repositorio
				uses: actions/checkout@v4

			- name: Configurar Node.js
				uses: actions/setup-node@v4
				with:
					node-version: '20'
					cache: 'npm'

			- name: Instalar dependencias
				run: npm ci

			- name: Ejecutar linter
				run: npm run lint

			# - name: Ejecutar pruebas
			# 	run: npm test
